version: '2'

services:

  db:
    image: postgres:13.4
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build: .
    user: 1001:1001
    container_name: recipes_app
    links:
      - db
    restart: unless-stopped
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=${PHX_HOST}
      - LETSENCRYPT_HOST=${PHX_HOST}
      - PHX_HOST
      - DATABASE_URL
      - SECRET_KEY_BASE
    volumes:
      - photos:/app/lib/recipes-0.3.3/priv/static/photos

networks:
  default:
    name: nginx-proxy
    external: true
volumes:
  photos:
  data:
