version: '2'

services:

  db:
    image: postgres:13.4
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
  app:
    build: .
    links:
      - db
    restart: unless-stopped
    ports:
      - 4000
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=${PHX_HOST}
      - LETSENCRYPT_HOST=${PHX_HOST}
      - PHX_HOST
      - DATABASE_URL
      - SECRET_KEY_BASE
    volumes:
      - photos:/app/lib/recipes-0.2.0/priv/static/photos

networks:
  default:
    name: nginx-proxy
    external: true
volumes:
  photos:
