version: '2'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER:
      POSTGRES_DB:

  adminer:
    image: adminer
    restart: unless-stopped
    links:
      - postgres
    ports:
      - 8786:8080
